"""Protocols for robots, action sources, and dataset writers."""

from __future__ import annotations

from typing import Protocol

from fr3_dexterous_platform.schemas import Action, CollectionConfig, Observation, StepRecord


class RobotBackend(Protocol):
    def connect(self) -> None: ...

    def disconnect(self) -> None: ...

    def get_observation(self) -> Observation: ...

    def send_action(self, action: Action) -> Action: ...


class ActionSource(Protocol):
    def connect(self) -> None: ...

    def disconnect(self) -> None: ...

    def reset(self) -> None: ...

    def get_action(self, observation: Observation) -> Action: ...


class EpisodeWriter(Protocol):
    def start_episode(self, config: CollectionConfig) -> None: ...

    def write_step(self, step: StepRecord) -> None: ...

    def close_episode(self) -> None: ...

    def finalize(self) -> None: ...
