from typing import Any

class MCPSettings:
    def set_udp(self, port: int) -> None: ...
    def set_bvh_rotation(self, rotation: int) -> None: ...

class MCPApplication:
    def set_settings(self, settings: MCPSettings) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def poll_next_event(self) -> list[Any]: ...

class MCPJoint:
    def get_name(self) -> str: ...
    def get_local_position(self) -> tuple[float, float, float] | None: ...
    def get_local_rotation(self) -> tuple[float, float, float, float]: ...
    def get_tag(self) -> int: ...
    def get_parent_joint_tag(self, tag: int) -> int: ...
    def get_name_by_tag(self, tag: int) -> str: ...

class MCPAvatar:
    def get_joints(self) -> list[MCPJoint]: ...

class MCPEventType:
    AvatarUpdated: int
